### ISSUE TITLE
Fullscreen images in chrome and opera choppy

### ISSUE THREAD

**Issue by anim3ghos7** [LeahArmstrong/fullpage.scss#2]
When using images in the slider in chrome or opera the animation is very choppy depending on the computer viewing the page. Also, when the slider returns to the first slide it doesn't render the image correctly until the screen is scrolled or moved.
![screenshot](https://cloud.githubusercontent.com/assets/22245675/18599187/b0dc50d8-7c1c-11e6-8ed3-f6a937236b93.png)

**Comment by DustinArmstrong** [comment]
Should be resolved with 64a13085e0c5e93263659352edb21e71c3f49802

Updated to `transform: translate3d()` which should avoid repainting. Worked in Chrome/Opera/Safari/Firefox with an image as the first slide. Browser prefixes have been removed as well, so keep this in mind while maintaining your codebase if you update `_fullpage.scss`

**Comment by anim3ghos7** [comment]
Thanks for the update Dustin, it will now render the image correctly when it goes back to the first slide. However, now none of the other images will display in chrome.  Here's a link to the project if you wanna take a look http://creativetest.kissr.com. The images display with the old version but not with the new 'translate3d' version. I'll look through my code in case there's something wrong there, I can't think of what it could be but I'll play around with it.

**Comment by DustinArmstrong** [comment]
@anim3ghos7 I'll work on another push for this, but remove the `overflow: visible` from [here](https://github.com/DustinArmstrong/fullpage.scss/blob/master/assets/scss/_fullpage.scss#L84) and let me know if that fixes it.

**Comment by anim3ghos7** [comment]
I removed the overflow: hidden and it still won't display the images. Inspector in Chrome shows the images are there when viewing the css but will only display the background color.

**Comment by anim3ghos7** [comment]
@DustinArmstrong I removed the background-attachment: fixed from my css and that seems to have corrected the issue with both versions of your code. This works for me and I don't think it would be that big an issue for others. Thanks for all your help!
